### ISSUE TITLE
Tutorials Test Fails on Windows 

### ISSUE THREAD

**Issue by aladshaw3** [nawi-hub/proteuslib#149]
The tutorials test fails for me on Windows. I installed proteuslib using a conda environment on Windows using Anaconda. All tests pass except for <code>test_tutorials.py</code>. Issue was that my Anaconda shell could not find module <code>win32api</code>. I could resolve the issue by doing <code>conda install pywin32</code>. 

Should we have this in requirements or installation instructions? Has anyone else experienced this issue?

**Comment by lbianchi-lbl** [comment]
Thanks for reporting this. I think that adding `win32api` to the dependencies would be a reasonable option, however, I'd have expected that it should already be required by our dependencies when installing on Windows, particularly the IPython/Jupyter machinery through `idaes-pse`.

Can you try to run these commands in the same Conda environment, and paste the output?

- `python -c "from platform import uname; print(uname())"`
- `conda list`
- `pip list`
- `pip show idaes-pse`
- `pip show win32api`

**Comment by aladshaw3** [comment]
> Thanks for reporting this. I think that adding `win32api` to the dependencies would be a reasonable option, however, I'd have expected that it should already be required by our dependencies when installing on Windows, particularly the IPython/Jupyter machinery through `idaes-pse`.
> 
> Can you try to run these commands in the same Conda environment, and paste the output?
> 
> * `python -c "from platform import uname; print(uname())"`

uname_result(system='Windows', node='LAP0120472', release='10', version='10.0.18363', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 12, GenuineIntel')

> * `conda list`

packages in environment at C:\Users\1pi\Miniconda3\envs\proteuslib-dev:

Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-shutil-get-terminal-size 1.0.0                    pypi_0    pypi
black                     21.6b0                   pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
bunch                     1.0.1                    pypi_0    pypi
ca-certificates           2021.5.30            h5b45459_0    conda-forge
certifi                   2021.5.30        py38haa244fe_0    conda-forge
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  5.5                      pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dataclasses-json          0.5.4                    pypi_0    pypi
debugpy                   1.3.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
fastjsonschema            2.15.1                   pypi_0    pypi
flask                     2.0.1                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
idaes-pse                 1.10.1                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.0.0                    pypi_0    pypi
ipython                   7.25.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
json-schema-for-humans    0.33.2                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
linkify-it-py             1.0.1                    pypi_0    pypi
lxml                      4.6.3                    pypi_0    pypi
markdown-it-py            1.1.0                    pypi_0    pypi
markdown2                 2.4.0                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
marshmallow               3.12.1                   pypi_0    pypi
marshmallow-enum          1.5.1                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
myst-parser               0.15.1                   pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.1.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.4.0                    pypi_0    pypi
numpy                     1.21.0                   pypi_0    pypi
openssl                   1.1.1k               h8ffe710_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.5                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.0                    pypi_0    pypi
pint                      0.17                     pypi_0    pypi
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1                   pypi_0    pypi
ply                       3.11                     pypi_0    pypi
prometheus-client         0.11.0                   pypi_0    pypi
prompt-toolkit            3.0.19                   pypi_0    pypi
proteuslib                0.2.0.dev0                dev_0    <develop>
psutil                    5.8.0                    pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pymongo                   3.11.4                   pypi_0    pypi
pyomo                     6.0.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
pytest                    6.2.4                    pypi_0    pypi
pytest-cov                2.12.1                   pypi_0    pypi
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywin32                   301                      pypi_0    pypi
pywinpty                  1.1.3                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qtconsole                 5.1.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
rbfopt                    4.2.2                    pypi_0    pypi
regex                     2021.4.4                 pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
send2trash                1.7.1                    pypi_0    pypi
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sphinx                    4.0.2                    pypi_0    pypi
sphinx-rtd-theme          0.5.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.36.0               h8ffe710_0    conda-forge
stringcase                1.2.0                    pypi_0    pypi
sympy                     1.8                      pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
tinydb                    4.5.0                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
typing-inspect            0.7.1                    pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2             py38haa244fe_1006    conda-forge

> * `pip list`

Package                            Version             Location
---------------------------------- ------------------- --------------------------------
alabaster                          0.7.12
appdirs                            1.4.4
argon2-cffi                        20.1.0
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
Babel                              2.9.1
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
black                              21.6b0
bleach                             3.3.0
bunch                              1.0.1
certifi                            2021.5.30
cffi                               1.14.5
chardet                            4.0.0
click                              7.1.2
colorama                           0.4.4
coverage                           5.5
cycler                             0.10.0
dataclasses-json                   0.5.4
debugpy                            1.3.0
decorator                          4.4.2
defusedxml                         0.7.1
docutils                           0.16
entrypoints                        0.3
fastjsonschema                     2.15.1
Flask                              2.0.1
Flask-Cors                         3.0.10
htmlmin                            0.1.12
idaes-pse                          1.10.1
idna                               2.10
imagesize                          1.2.0
iniconfig                          1.1.1
ipykernel                          6.0.0
ipython                            7.25.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
itsdangerous                       2.0.1
jedi                               0.18.0
Jinja2                             3.0.1
json-schema-for-humans             0.33.2
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyterlab-pygments                0.1.2
jupyterlab-widgets                 1.0.0
kiwisolver                         1.3.1
linkify-it-py                      1.0.1
lxml                               4.6.3
markdown-it-py                     1.1.0
markdown2                          2.4.0
MarkupSafe                         2.0.1
marshmallow                        3.12.1
marshmallow-enum                   1.5.1
matplotlib                         3.4.2
matplotlib-inline                  0.1.2
mdit-py-plugins                    0.2.8
mistune                            0.8.4
mpmath                             1.2.1
mypy-extensions                    0.4.3
myst-parser                        0.15.1
nbclient                           0.5.3
nbconvert                          6.1.0
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.5.1
notebook                           6.4.0
numpy                              1.21.0
packaging                          20.9
pandas                             1.2.5
pandocfilters                      1.4.3
parso                              0.8.2
pathspec                           0.8.1
pickleshare                        0.7.5
Pillow                             8.3.0
Pint                               0.17
pip                                21.1.3
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.11.0
prompt-toolkit                     3.0.19
proteuslib                         0.2.0.dev0          c:\users\1pi\projects\proteuslib
psutil                             5.8.0
py                                 1.10.0
pycparser                          2.20
Pygments                           2.9.0
pymongo                            3.11.4
Pyomo                              6.0.1
pyparsing                          2.4.7
pyrsistent                         0.18.0
pytest                             6.2.4
pytest-cov                         2.12.1
python-dateutil                    2.8.1
python-slugify                     5.0.2
pytz                               2021.1
pywin32                            301
pywinpty                           1.1.3
PyYAML                             5.4.1
pyzmq                              22.1.0
qtconsole                          5.1.1
QtPy                               1.9.0
rbfopt                             4.2.2
regex                              2021.4.4
requests                           2.25.1
scipy                              1.7.0
Send2Trash                         1.7.1
setuptools                         49.6.0.post20210108
six                                1.16.0
snowballstemmer                    2.1.0
Sphinx                             4.0.2
sphinx-rtd-theme                   0.5.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
stringcase                         1.2.0
sympy                              1.8
terminado                          0.10.1
testpath                           0.5.0
text-unidecode                     1.3
tinydb                             4.5.0
toml                               0.10.2
tornado                            6.1
traitlets                          5.0.5
typing-extensions                  3.10.0.0
typing-inspect                     0.7.1
uc-micro-py                        1.0.1
urllib3                            1.26.6
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           2.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
wincertstore                       0.2

> * `pip show idaes-pse`

Name: idaes-pse
Version: 1.10.1
Summary: IDAES Process Systems Engineering Framework
Home-page: https://idaes.org
Author: None
Author-email: None
License: BSD
Location: c:\users\1pi\miniconda3\envs\proteuslib-dev\lib\site-packages
Requires: rbfopt, nbconvert, sympy, lxml, pytest, requests, tinydb, click, bunch, python-slugify, scipy, pandas, flask-cors, matplotlib, pyomo, pint, nbformat, flask, numpy, colorama, backports.shutil-get-terminal-size, jupyter, pyyaml, networkx, psutil
Required-by: proteuslib

> * `pip show win32api`

WARNING: Package(s) not found: win32api

**Comment by aladshaw3** [comment]
Interestingly, <code>pywin32</code> shows up in both the 'pip' list and 'conda' list, but doing <code>pip show win32api</code> says it cannot find the package.

**Comment by lbianchi-lbl** [comment]
> Interestingly, `pywin32` shows up in both the 'pip' list and 'conda' list, but doing `pip show win32api` says it cannot find the package.

Thanks for running all these checks! I think the reason why `pip show pywin32` is because it was installed using `conda` rather than `pip` (I quickly tried to look for a Conda equivalent of `pip show`, but couldn't find any).

**Comment by lbianchi-lbl** [comment]
This seems to be due to an well-known problem with Jupyter on Windows for Python 3.8 and up, see e.g. IDAES/idaes-pse#258. #151 adds Windows checks for PRs that are able to detect this or similar issues, and a workaround that solves this issue.
