### ISSUE TITLE
EDB: Fix how ions are defined in the schema and database

### ISSUE THREAD

**Issue by dangunter** [nawi-hub/proteuslib#163]
- [x] The "anion" and "cation" types are required to be associated with a "charge"
- [x] Defined "anion" and "cation" as "liquidPhase", but ions should be "aqueousPhase"

All issues are the ions-- if I remove the ions from the list of species I ask for, it builds fine

**Comment by aladshaw3** [comment]
For consistency, whenever I have ions in solution, I define all 'liquids' as 'aqeuousPhase'. Definitely the ions should be 'aqueousPhase', but I also define things like 'H2O' and 'H2CO3' as 'aqueousPhase' as well. Not sure how much that matters. It depends on how IDAES differentiates between 'liquidPhase' and 'aqueousPhase'.

**Comment by andrewlee94** [comment]
For the purposes of this, all electrolyte phases (i.e. phases containing ions) should be `aqueousPhases`. I believe IDAES will raise an Exception if you try to declare `Ions` in anything other than an `AqueousPhase`.

**Comment by dangunter** [comment]
I will change the word "liquid" to "aqueous"
