### ISSUE TITLE
Double-check 1D implementation

### ISSUE THREAD

**Issue by adam-a-a** [nawi-hub/proteuslib#192]
This issue serves as a reminder to go through the 1D implementation of the RO model again. There are still questions to consider, e.g., should the last node along the membrane channel also be skipped (like the inlet node)? Answering these questions will require another, more detailed look into Pyomo.DAE.

**Comment by andrewlee94** [comment]
Regarding the last node, the answer is no. You should write the full set of equations at all nodes except the inlet boundary (and some argue you should even write the equations there as well).

**Comment by adam-a-a** [comment]
Originally, I wasn't skipping the inlet, and this resulted in violation of mass conservation. After adding the Constraint.Skip at the inlet for relevant constraints, everything began to work (mass conservation satisfied).

**Comment by andrewlee94** [comment]
My guess is that is because you were calculating a mass transfer term there which you were using in the overall transfer calculation, but was not being included in the material balances (this is why we generally skip the inlet node).

**Comment by adam-a-a** [comment]
Now that I think back, I think that was exactly what the issue was!

**Comment by adam-a-a** [comment]
Nevertheless, I want to keep this issue around for any additional discussion on 1D implementation, especially if @TimBartholomew wants to discuss the topic further.
