### ISSUE TITLE
Add warning to the developer installation docs about side effects of `--force-reinstall` pip flag

### ISSUE THREAD

**Issue by lbianchi-lbl** [nawi-hub/proteuslib#193]
As correctly pointed out by @srikanthallu , `pip install --force-reinstall` will cause *all* packages in the current environment to be reinstalled from scratch.

This is a destructive operation that could severely affect developers if they run this in a long-lived environment with many custom-installed packages. Even though we probably don't want to encourage this workflow, the documentation should at least include a warning for the user of what the consequences of the `--force-reinstall` flag will be.

**Comment by adam-a-a** [comment]
@lbianchi-lbl Could `pip install --upgrade --force-reinstall <package>` be a possible alternative?

**Comment by adam-a-a** [comment]
@lbianchi-lbl More alternatives are listed [here](https://sparrow.dev/pip-force-reinstall/)

You probably already considered such options, but I thought there might be a chance that this could be useful.

**Comment by lbianchi-lbl** [comment]
Thanks @adam-a-a for the suggestions, I actually don't have a lot of experience with upgrading existing environments using pip so I think it's very useful to look into the various alternatives in more detail.

The issue with `--upgrade` is that it depends on the package being installed having a newer version than the one already installed, which in turn requires the version information being accessible to pip when installing, which is likely not the case with our current versioning setup. Therefore, I'd have to double-check to understand what the difference would be between `--upgrade --force-reinstall` and `--force-reinstall` by itself.

The other issue is the dependencies: does `--force-reinstall` affect the package being installed and its direct dependencies only, or are there cases where other non-dependent packages are also affected? I checked the official pip docs to see if there was more information about this, but it's not immediately clear. 

All in all, I think it could be worth to simply sit down and try the various combinations, and compare the results (e.g. by running `pip freeze > some-file.txt` before and after each flag combination being tested), having the current basic guide (plus the caveats/warnings) in the meantime.

**Comment by lbianchi-lbl** [comment]
Following @dangunter's suggestion, a safer alternative is to `pip uninstall`ing the package and then `pip install`ing it again (with the `--no-cache-dir` option).

**Comment by lbianchi-lbl** [comment]
Addressed by #202.
