### ISSUE TITLE
Add documentation for unit models

### ISSUE THREAD

**Issue by TimBartholomew** [nawi-hub/proteuslib#42]
Current unit model documentation (NF and RO) needs to more directly state the variables, constraints, and general case (i.e. degrees of freedom).

**Comment by adam-a-a** [comment]
- [x] Tech spec for 0D RO

Although the existing NF documentation is in a different format than what we are using now, I think our time would be better spent revising the technical specification doc once the NF model itself is revisited and revised. 

I think we can close this issue and create a new one specifically for improving the NF model and its documentation for the September release. @TimBartholomew Do you agree?
