### ISSUE TITLE
Add reports to unit models

### ISSUE THREAD

**Issue by TimBartholomew** [nawi-hub/proteuslib#56]
Currently the unit models do not include the methods to support reports. These should be added.

**Comment by adam-a-a** [comment]
**Note:** `process_base.py` contains the `report()` method, which calls both `_get_performance_contents()` and `_get_stream_table_contents()` methods. There is also the `serialize_contents()` method which returns both performance contents and stream table but can possibly result in a ConfigurationError if inlets/outlets of unit model are atypical.

- [ ] Add `_get_performance_contents()` method to unit models in the following format, based on IDAES unit model documentation: 
````
def _get_performance_contents(self, time_point=0):
    var_dict = {"display name": self.var[time_point]}
    expr_dict = {"display name": self.expr[time_point]}
    param_dict = {"display name": self.param[time_point]}

    return {"vars": var_dict, "exprs": expr_dict, "params": param_dict}
````
- [ ] Add `_get_stream_table_contents()` method
- [ ] Include `report()` when updating RO (or future) tutorial

**Comment by adam-a-a** [comment]
Running TO-DO: 

- [ ] Add report() call to RO tutorial
- [ ] Add reporting to NF model
- [ ] Add reporting to ERD
- [ ] Add reporting to Pump

**Comment by adam-a-a** [comment]
Reopening this issue since on item on the task list has not been merged yet.
