### ISSUE TITLE
Improve initialization for RO and property packages

### ISSUE THREAD

**Issue by TimBartholomew** [nawi-hub/proteuslib#91]
Currently the initialization routine for RO is not stable. In multiple flowsheets and cases, it fails to find the feasible solution. The initialization can be improved via the following:

- [x] initialize the interface state blocks, currently they are not being initialized before the unit model solve
- [x] update default values in the property packages to be more reasonable, i.e. current default values for component mass flowrate is 1 for solvents and solutes. The solutes should be 10 or 100 times smaller than the solvent
- [x] check the degrees of freedom in the initialization routine and raise an error if it is not 0, there are currently no checks for the degrees of freedom

**Comment by adam-a-a** [comment]
@TimBartholomew do we want to add an assert dof == 0 _in_ the initialize() method for RO or the property model? Actually, do we want to add this in any initialize() method at all? I thought that the user could add the assert statement before the initialize method in a simulation file; nevertheless, I suppose it wouldn't hurt to have an assert statement carried out before AND within the initialize method.

**Comment by andrewlee94** [comment]
@adam-a-a We have generally said that initialize functions should assert degrees of freedom. Initialization routines generally assume this, and if this is not true we cannot guarantee the behaviour of the routine or the final result. Hence, we have generally forced the user to fix the degrees of freedom and fail if this is not true - if the user really wants to initialize with degrees of freedom, they should write their own routine.

**Comment by adam-a-a** [comment]
@TimBartholomew  Do you think the merging of #173 justifies closing this issue? In my opinion any overflow from this issue could be covered by issue #132.
