### ISSUE TITLE
Identify properties that aren't built in RO model to avoid misreporting

### ISSUE THREAD

**Issue by adam-a-a** [nawi-hub/proteuslib#93]
While testing one of the LSRRO simulation files, I noticed that the osmotic pressure of the final brine discharge was being displayed, and the value was erroneously low. After further investigation, I realized that the osmotic pressure of the _bulk_ solution at the RO outlet was not being called, and properties are set up to be built on demand. Since we modified the RO model to include state blocks for the inlet/outlet of the membrane interface (#11), the bulk osmotic pressure is no longer called in the RO model; instead, the osmotic pressure at the membrane interface is called. Thus, if the user wanted to display the bulk osmotic pressure at the RO outlet, he or she would get the initialized value from that property model. For example, the default value for osmotic pressure in the NaCl property model is 10 bar, and this is the value that was displayed for the bulk osmotic pressure of a high-salinity brine.

This is the only example I stumbled upon, but we should probe further to identify any properties that are not called in the RO model in a given state block and ensure that none of these would be of interest to a user. Otherwise, he or she will try to report said value expecting to get a calculated value, and this will either result in (i) misreporting, (ii) cascading error if any post-processing/calculations are conducted, or (iii) the user thinking that model calculations are incorrect when the actual problem is that the model just didn't perform the calculation.

Furthermore, we should provide a remedy for this, which may entail modifications in the RO model.

**Comment by TimBartholomew** [comment]
Generally, this is not a RO model issue as this type of user error is true of all IDAES models. We can provide better documentation (actually we currently have none) that lists for the user all the variables that are part of the model.

Whether or not that the bulk feed and retentate osmotic pressure is a property is up for discussion, I'm leaning away from that, but really it should come down to what we think is best for the user in the report method of the RO model.

**Comment by adam-a-a** [comment]
After the addition of the `over_pressure_ratio` variable in #84, the bulk osmotic pressure at the RO outlet is no longer unused. Thus, the value would be reported correctly if called after a solve. For the time being, it seems like this issue is longer a problem for the RO model.

However, I should note that the `unused_variables_set` and `number_unused_variables` functions don't seem to descend into the model, so in our tests, the true number of unused variables might be missed unless we call each block--or at least that is my interpretation; this might merit further discussion but is currently low priority.

**Comment by andrewlee94** [comment]
@adam-a-a I didn't bother checking to confirm, but you should be able to provide the argument `descend_into=True` to the model statistics methods to tell them to descend into child blocks.

**Comment by adam-a-a** [comment]
@andrewlee94 That seems to be the case for several of the methods in model statistics, but it looks like `unused_variables_set` and `number_unused_variables` don't have the `descend_into` argument.

**Comment by adam-a-a** [comment]
Ah, but `variables_set` and `variables_in_activated_constraints_set` do use `descend_into`, and unused_variables_set returns `variables_set(block) - variables_in_activated_constraints_set(block)`

**Comment by adam-a-a** [comment]
We may want to consider adding an optional method that constructs other build-on-demand properties that aren't currently used in model constraints (and thus are never built) but would still be of interest to the user (e.g., bulk osmotic pressure of the feed is not directly constructed).

**Comment by adam-a-a** [comment]
PR #162 addresses this issue for 1DRO by adding a boolean `has_full_reporting` config argument and associated methods to generate a "full" report.

The same needs to be applied in 0D RO now. 

Notably, using the IDAES Property Interrogator tool can reveal all the properties that the RO model uses. If there were a utility function that (1) generated a list of required properties for a unit model (i.e., Property Interrogator does this), (2) generated a list of available properties for a given property model, and (3) subtracted the intersection between these two lists, we'd get the additional properties that could/should be added to a "full' report. I am unaware of whether such a utility function exists already.

**Comment by andrewlee94** [comment]
There is no tool that does that, as there are some challenges due to the build-on-demand approach.

However, there is a way to temporarily disable build-on-demand properties, which would allow you to use normal `if hasattr(model, prop)` approaches to determine what properties are present and to include them as needed.

**Comment by adam-a-a** [comment]
> There is no tool that does that, as there are some challenges due to the build-on-demand approach.
> 
> However, there is a way to temporarily disable build-on-demand properties, which would allow you to use normal `if hasattr(model, prop)` approaches to determine what properties are present and to include them as needed.

Would that way be `self._lock_attribute_creation = True` ?

**Comment by andrewlee94** [comment]
@adam-a-a Yes, that is it - you use the Python `with` command.

**Comment by adam-a-a** [comment]
Since the issue can be resolved by adding the `has_full_reporting` config argument and associated methods (as in the 1DRO model), I think we can close this issue. The idea for a tool to deal with this is mentioned above and can be revisited at a later time.
